language: java
notifications:
  slack:
    secure: J/yoDyrrVH9yriD6wuqWPzCVmdMsAqSS7kRVAODs8leV9gHrhDvOTljjQvZx2mYkt08bJKtbzxT1AdHTgb3ieqMVt0uy9NpG+ucLrkJZZIHIjydrEXBf9yw6jfzFccybFm6SLjKxIQOG6n0ycvr2Koh7GkGp+yno4wGUbQ95ZrsJmBbZmxrH0NokkXheYjx89ZgdbHixXhd0rowMSntw/ycAGIWwQ9UvNOSY0mJWuYxaFrWNe/TyFLULoYJSaguYpg/f9ZBqmMaewvg0I+8qM/kxoikiuwPvqa58HQVlzzKbLZEPRWj20bey7qK25LsA/9phH7zy+9gjDbQK1nnYkgCTBuc7AzEvFAP8ppHmTX9NbI7vHgMfsjqaArLxpm5YzlFqzqA9B6xieLSmUOyo0ty+f44F8OFPmUfdZjzfre3JSxmLfVur/BZBNWlCq1OVSDJ1gwsa8TZzwKJeWyWGgrBbsSK0vutyKDQB4TSzGfUJnUdaCdOnA9HkqVwDx7PtoVXWHgLl7oSgAK7C62mZShaJlRCoKvxskJauHAKUuifK7kcs8m7RlWWeXeAGwY7S9BE8VgCyHmzaJWKoxBgnysgzPLl9NX8IW/S0kF+z8T+nUKS4dMyY4pJwPOuTx4v7pLVbQtezXI/+IWGorhHrWSLKrTPEacEIih0Sd8rOke4=
deploy:
  provider: releases
  api_key:
    secure: ZOsNYoEc55YUIoWapnsJQXaGvayf4IMs9WUJqstQ1HMwbfL64Nsr7piir5rLRZG2yzpQbNm6Gsu8nrAI/Q10M0RMMGjy6BLNRaPz+288H5/x6pVtOmw/S4OVUYyax/jdXQ3wOQn9bNAVCiJE2YAl4wMDuFjKXoSK5glTe/I6ZkPV3j7lhIYmLlc6deFcN9ViC2QbacMuWush3Gf3p67/kF1t00OBa2g6uvmsFHgtsx0z3COT5b71IBDtb1fvfPesyzTum3Hvz+/pP0OwKntTeVxkvZjeW3wNNF8L3eom+8wDsLu9CW8XX2YGho5oy7bQEAnHuheXg2uoQG7DKLlp5LymXPBMAH3a3z//vRy6rW8dCvgk8078azBHwghiJpzCr7GjpkGL0MmJFiSBmsaTR64fCXEuv1ScX54eWAAGeH4igUQ42frsVZOJ4v5kCFnmc67nmUaS7yUOajeKYKjT9C9eiHzghIblsY0sVjph1fVTFLLjyaQW39kftgGVs2whnRVrVpdGtIrg29g8N+YleF7b8sFV75a+zGiXjO542fs0ox4iTsOIbINOljhJg0XWxhrp2DBOCdKs4MQcCr2vuMi/YEoO92em8WfCduIzEC1sytYPvXKWPSu17LbiisW0O5ng3QWtg9RKIE7NhDEzYN8KJYdqXLwO1jlurLV4+Hw=
  file: build/libs/xlr-loadrunner-plugin-2.1.2.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-loadrunner-plugin
